name: ci
on: [push, pull_request]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v4

      - name: Setup pnpm 📦
        uses: pnpm/action-setup@v4

      - name: Setup Node 🥣
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: pnpm

      - run: node -v
      - run: pnpm -v

      - name: Install dependencies 📦
        run: pnpm install --frozen-lockfile

      - name: Build
        # run: pnpm run build
        # Public peer server is down for the moment -> we use a local signaling server
        run: pnpm run build:peer-server

      - name: Lint
        run: pnpm run lint

      - name: Unit tests
        run: pnpm run test

      - name: End2end tests
        # run: JEST_TIMEOUT=30000 pnpm run test:e2e:start-server-and-test
        # Public peer server is down for the moment -> we use a local signaling server
        run: JEST_TIMEOUT=30000 pnpm run test:e2e:start-server-and-test:peer-server
